#pragma once

#define FIRMWARE_VERSION "v{{VERSION}}"
#define ENABLE_USER_AUTH
// #define ENABLE_CAPTIVE_MODE
#define SOFTAP_HOMELINK_SSID "Prime HomeLink"
#define SOFTAP_HOMELINK_PASSWORD ""
#define SOFTAP_NETWORK_OPEN 1
#define EEPROM_SIZE 128
#define SSID_ADDR 0
#define PASS_ADDR 32
#define FLAG_ADDR 96
#define FLAG_FB_SETUP 98
#define FLAG_FIRESTORE_SETUP 97
#define RECONNECT_TIME_INTERVEL 5000
#define HEART_BEAT_INTERVAL 60*1000
#define DNS_PORT 53
#define FB_API_KEY "REMOVED_FIREBASE_KEY"
#define FIREBASE_PROJECT_ID "prime-homelink"